Add Kyverno README
mia-platform/distribution pull request #10
Opened 2023-02-10 11:44 UTC by JGiola

## What this PR is for?

It will add the README for the Kyverno module

2023-02-10 14:10 UTC, emanuele232 commented on modules/security/kyverno/README.md
> +functionality are restricted.
```suggestion
Kyverno is a Kubernetes policy manager that leverages CRDs to enforce policies at cluster or namespace level. These policies filter what is been deployed and ensure that they meet the defined security specifications or that some functionality are restricted.  
```

2023-02-10 14:10 UTC, emanuele232 commented on modules/security/kyverno/README.md
> +or ensuring that certain fields are automatically compiled.
```suggestion
Kyverno can also patch resources at apply time or generate them from scratch in order to automate certain features
or ensure that necessary fields are automatically compiled.
```

2023-02-10 14:14 UTC, emanuele232 commented on modules/security/kyverno/README.md
> +No customization is needed, you have to create your `Policies` or `ClusterPolicies` to apply to your cluster,
```suggestion
No customization is needed to use Kyverno, you can start by defining your `Policies` or `ClusterPolicies` and apply them your cluster.
```

2023-02-10 14:14 UTC, emanuele232 commented on modules/security/kyverno/README.md
> +in the [documentation](https://kyverno.io/policies/).
```suggestion
To view some examples, you can explore the [kyverno policies repository](https://github.com/kyverno/policies) or check them in the [documentation](https://kyverno.io/policies/).
```

2023-02-13 10:31 UTC, fiscafusca requested changes

2023-02-13 10:31 UTC, fiscafusca commented on modules/security/kyverno/README.md
> +Kyverno is a Kubernetes policy manager that leverages CRDs to enforce policies at cluster or namespace level. These policies filter what is been deployed and ensure that they meet the defined securit
```suggestion
Kyverno is a Kubernetes policy manager that leverages CRDs to enforce policies at the cluster or namespace level. These policies filter what is being deployed, and ensure that they meet the defined security specifications or that some functionalities are restricted.  
```

2023-02-13 10:31 UTC, fiscafusca commented on modules/security/kyverno/README.md
> +  - **Configs:** configuration and network policies for Kyverno
```suggestion
  - **Configs:** configurations and network policies for Kyverno
```

2023-02-13 10:42 UTC, fiscafusca approved these changes

2023-02-13 10:43 UTC, merged