feat: add readme for logging operator add-on
mia-platform/distribution pull request #18
Opened 2023-02-13 11:14 UTC by emanuele232

## What this PR is for?
add a readme for the addon logging-operator/logging-system. This add-on adds the configuration for fluentd and fluentbit

2023-02-13 11:27 UTC, fiscafusca requested changes

2023-02-13 11:27 UTC, fiscafusca commented on addons/logging-operator/logging-stack/README.md
> +This add-on define and deploys the logging system of the Logging operator. It consists of the necessary `FluentD` and `FluentBit` configurations.
```suggestion
This add-on defines and deploys the logging stack of the Logging operator. It consists of the necessary `FluentD` and `FluentBit` configurations. 
```

2023-02-13 11:27 UTC, fiscafusca commented on addons/logging-operator/logging-stack/README.md
> +- **Networkpolicies:** Networkpolicy neede to allow traffic for FluentBit.
```suggestion
- **Logging:** Logging CRD that defines configurations for FluentD and FluentBit.
- **Network policies:** Network policy needed to allow traffic for FluentBit.
```

2023-02-13 11:27 UTC, fiscafusca commented on addons/logging-operator/logging-stack/README.md
> +No customization is needed
```suggestion
No customization is needed. The add-on is ready-to-use.
```

2023-02-13 11:38 UTC, fiscafusca approved these changes

2023-02-13 11:42 UTC, fiscafusca requested changes

2023-02-13 11:42 UTC, fiscafusca commented on addons/logging-operator/logging-stack/README.md
> +
```suggestion
To work properly it needs the Logging Operator module.

```

2023-02-13 11:42 UTC, fiscafusca commented on addons/logging-operator/logging-stack/README.md
> +| 1.0.0          | 1.24.0                      | 1.24.0                    |
```suggestion
| Add-On Version | Logging Operator Module Version |
|----------------|---------------------------------|
| 1.0.0          | 1.24.0                          |
```

2023-02-14 08:33 UTC, JGiola approved these changes

2023-02-14 08:34 UTC, merged