feat: add prometheus monitoring stack
mia-platform/distribution pull request #27
Opened 2023-02-14 13:59 UTC by emanuele232

## What this PR is for?
the PR adds the readme for the monitoring stack addon

2023-02-15 08:31 UTC, JGiola requested changes

2023-02-15 08:31 UTC, JGiola commented on addons/prometheus-operator/monitoring-stack/README.md
> +It configures the `Prometheus` and `Alertmanager` resources, `kube-state-metrics`, and the `Monitors` that enable harvesting the metrics.
```suggestion
It configures `Prometheus` and `Alertmanager` custom resources, `kube-state-metrics`, `node-exporter` and the `Monitors` that enable harvesting the metrics.

```

2023-02-15 10:31 UTC, fiscafusca approved these changes, later dismissed

2023-02-15 10:31 UTC, fiscafusca commented on addons/prometheus-operator/monitoring-stack/README.md
> +- **Prometheus-operator:** Defines the ServiceMonitor needed to track the `prometheus-operator` services.
```suggestion
- **Alertmanager:** Defines the `Alertmanager` resource with its configurations.
- **Dns-service:** Defines the `podMonitor` resource needed to track the cluster's `dns services`.
- **Kube-state-metrics:** Defines the `podMonitor` resource needed to track the cluster's `kube*` pods.
- **Kubelet:** Defines the `podMonitor` resource needed to track the kubelet's services.
- **Node-exporter:** Defines the `podMonitor` resource needed to track the cluster's `node-exporter` pods.
- **Prometheus:** Defines the `Prometheus` resource with its configurations.
- **Prometheus-operator:** Defines the `ServiceMonitor` resource needed to track the `prometheus-operator` services.
```

2023-02-15 10:31 UTC, fiscafusca commented on addons/prometheus-operator/monitoring-stack/README.md
> +No customization is needed
```suggestion
No customization is needed. The add-on is ready-to-use.
```

2023-02-21 17:07 UTC, JGiola approved these changes

2023-02-21 17:08 UTC, merged