Feat/observability metrics server
mia-platform/distribution pull request #31
Opened 2023-10-16 15:22 UTC by ddellarocca

## What this PR is for?
Addition of the metrics-server.
This PR adds the metrics-server module.

2023-11-15 10:03 UTC, JGiola requested changes
Thank you for the module, I've added some minor comments and suggestions before merging it.

2023-11-15 10:03 UTC, JGiola commented on modules/observability/metrics-server/CHANGELOG.md
> +## v1.26.0
```suggestion
```

We don't aim to release the module for the 1.26 version, so we can remove this from the changelog

2023-11-15 10:03 UTC, JGiola commented on modules/observability/metrics-server/README.md
> +- check TLS when to nodes
```suggestion
- check TLS validity when connecting to the kubelet
```

2023-11-15 10:03 UTC, JGiola commented on modules/observability/metrics-server/base/resources/workloads/metrics-server/api-service.yaml
> +  insecureSkipTLSVerify: true
There is a way to allow us to flip this flag to true?

2023-11-15 10:03 UTC, JGiola commented on modules/observability/metrics-server/base/resources/rbac/clusterroles.yaml
> +    rbac.authorization.k8s.io/aggregate-to-view: "true"
Minor thing, based on how the aggregation works we can leave only the `aggregate-to-view` label and the others will pick it up the same
```suggestion
    rbac.authorization.k8s.io/aggregate-to-view: "true"
```

2023-11-15 10:03 UTC, JGiola commented on modules/observability/metrics-server/base/resources/workloads/kustomization.yaml
> +apiVersion: kustomize.config.k8s.io/v1beta1
```suggestion
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/instance: metric-server
  app.kubernetes.io/name: metric-server
```

Can we add this two additional labels to uniform it to the other modules?

2023-11-15 10:03 UTC, JGiola commented on modules/observability/metrics-server/base/resources/workloads/metrics-server/api-service.yaml
I was thinking if is not better to handle this file like a crd, and move it at the top of the modules inside an `apiservices` folder...

2023-11-21 13:17 UTC, ddellarocca commented on modules/observability/metrics-server/base/resources/workloads/metrics-server/api-service.yaml
> +  insecureSkipTLSVerify: true
Tried but it is not working. We can try to use cert-manager in order to generate and mange its certificate.

2023-11-27 09:08 UTC, JGiola commented on modules/observability/metrics-server/base/resources/workloads/metrics-server/api-service.yaml
> +  insecureSkipTLSVerify: true
We can left if for a future improvement for now

2023-11-27 09:08 UTC, JGiola approved these changes

2023-11-27 09:09 UTC, merged